version: "3.8"
# this is for development purpose only
services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: karan
      MONGO_INITDB_ROOT_PASSWORD: Kumar1234 # (change here if needed)
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--username",
          "karan",
          "--password",
          "Kumar1234",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: karan
      ME_CONFIG_MONGODB_ADMINPASSWORD: Kumar1234
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: karan
      ME_CONFIG_BASICAUTH_PASSWORD: Kumar1234

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight UI
    volumes:
      - redis-data:/data

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

volumes:
  mongo-data:
  redis-data:
  redpanda-data:
